<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="graph-snaps" timestamp="2023-07-24T11:44:11Z" hostname="a61fa3a838a6" tests="17" skipped="7" failures="0" errors="4" time="6.413">
    <testcase time="2.90200000000004" classname="graph_snaps" name="plot_v1">
      <skipped message="Reason: On CRAN ('test-graph-snaps.R:53:9')"/>
    </testcase>
    <testcase time="0.564000000000078" classname="graph_snaps" name="plot_v2">
      <skipped message="Reason: On CRAN ('test-graph-snaps.R:53:9')"/>
    </testcase>
    <testcase time="0.600999999999885" classname="graph_snaps" name="plot_v3">
      <skipped message="Reason: On CRAN ('test-graph-snaps.R:53:9')"/>
    </testcase>
    <testcase time="0.764000000000124" classname="graph_snaps" name="plot_v4">
      <skipped message="Reason: On CRAN ('test-graph-snaps.R:53:9')"/>
    </testcase>
    <testcase time="0.0950000000000273" classname="graph_snaps" name="plot_v51">
      <error type="error" message="Error in `stat_summary(fun = mean, linewidth = 1, geom = &quot;line&quot;, aes(group = 1,  ('test-graph-snaps.R:53:9')">Error in `stat_summary(fun = mean, linewidth = 1, geom = "line", aes(group = 1, 
    linetype = mean_95_text))`: Problem while computing aesthetics.
i Error occurred in the 3rd layer.
Caused by error:
! object 'mean_95_text' not found
Backtrace:
     x
  1. +-vdiffr::expect_doppelganger(...) at test-graph-snaps.R:53:8
  2. | \-vdiffr (local) writer(fig, testcase, title)
  3. |   +-vdiffr:::print_plot(plot, title)
  4. |   \-vdiffr:::print_plot.ggplot(plot, title)
  5. |     +-base::print(p)
  6. |     \-ggplot2:::print.ggplot(p)
  7. |       +-ggplot2::ggplot_build(x)
  8. |       \-ggplot2:::ggplot_build.ggplot(x)
  9. |         \-ggplot2:::by_layer(...)
 10. |           +-rlang::try_fetch(...)
 11. |           | +-base::tryCatch(...)
 12. |           | | \-base (local) tryCatchList(expr, classes, parentenv, handlers)
 13. |           | |   \-base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
 14. |           | |     \-base (local) doTryCatch(return(expr), name, parentenv, handler)
 15. |           | \-base::withCallingHandlers(...)
 16. |           \-ggplot2 (local) f(l = layers[[i]], d = data[[i]])
 17. |             \-l$compute_aesthetics(d, plot)
 18. |               \-ggplot2 (local) compute_aesthetics(..., self = self)
 19. |                 \-ggplot2:::scales_add_defaults(...)
 20. |                   \-base::lapply(aesthetics[new_aesthetics], eval_tidy, data = data)
 21. |                     \-rlang (local) FUN(X[[i]], ...)
 22. \-base::.handleSimpleError(...)
 23.   \-rlang (local) h(simpleError(msg, call))
 24.     \-handlers[[1L]](cnd)
 25.       \-cli::cli_abort(...)
 26.         \-rlang::abort(...)</error>
    </testcase>
    <testcase time="0.111999999999853" classname="graph_snaps" name="plot_v52">
      <error type="error" message="Error in `stat_summary(fun = mean, linewidth = 1, geom = &quot;line&quot;, aes(group = 1,  ('test-graph-snaps.R:53:9')">Error in `stat_summary(fun = mean, linewidth = 1, geom = "line", aes(group = 1, 
    linetype = mean_95_text))`: Problem while computing aesthetics.
i Error occurred in the 3rd layer.
Caused by error:
! object 'mean_95_text' not found
Backtrace:
     x
  1. +-vdiffr::expect_doppelganger(...) at test-graph-snaps.R:53:8
  2. | \-vdiffr (local) writer(fig, testcase, title)
  3. |   +-vdiffr:::print_plot(plot, title)
  4. |   \-vdiffr:::print_plot.ggplot(plot, title)
  5. |     +-base::print(p)
  6. |     \-ggplot2:::print.ggplot(p)
  7. |       +-ggplot2::ggplot_build(x)
  8. |       \-ggplot2:::ggplot_build.ggplot(x)
  9. |         \-ggplot2:::by_layer(...)
 10. |           +-rlang::try_fetch(...)
 11. |           | +-base::tryCatch(...)
 12. |           | | \-base (local) tryCatchList(expr, classes, parentenv, handlers)
 13. |           | |   \-base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
 14. |           | |     \-base (local) doTryCatch(return(expr), name, parentenv, handler)
 15. |           | \-base::withCallingHandlers(...)
 16. |           \-ggplot2 (local) f(l = layers[[i]], d = data[[i]])
 17. |             \-l$compute_aesthetics(d, plot)
 18. |               \-ggplot2 (local) compute_aesthetics(..., self = self)
 19. |                 \-ggplot2:::scales_add_defaults(...)
 20. |                   \-base::lapply(aesthetics[new_aesthetics], eval_tidy, data = data)
 21. |                     \-rlang (local) FUN(X[[i]], ...)
 22. \-base::.handleSimpleError(...)
 23.   \-rlang (local) h(simpleError(msg, call))
 24.     \-handlers[[1L]](cnd)
 25.       \-cli::cli_abort(...)
 26.         \-rlang::abort(...)</error>
    </testcase>
    <testcase time="0.0900000000001455" classname="graph_snaps" name="plot_v53">
      <error type="error" message="Error in `stat_summary(fun = median, linewidth = 1, geom = &quot;line&quot;, aes(group = 1,  ('test-graph-snaps.R:53:9')">Error in `stat_summary(fun = median, linewidth = 1, geom = "line", aes(group = 1, 
    linetype = median_80_text))`: Problem while computing aesthetics.
i Error occurred in the 3rd layer.
Caused by error:
! object 'median_80_text' not found
Backtrace:
     x
  1. +-vdiffr::expect_doppelganger(...) at test-graph-snaps.R:53:8
  2. | \-vdiffr (local) writer(fig, testcase, title)
  3. |   +-vdiffr:::print_plot(plot, title)
  4. |   \-vdiffr:::print_plot.ggplot(plot, title)
  5. |     +-base::print(p)
  6. |     \-ggplot2:::print.ggplot(p)
  7. |       +-ggplot2::ggplot_build(x)
  8. |       \-ggplot2:::ggplot_build.ggplot(x)
  9. |         \-ggplot2:::by_layer(...)
 10. |           +-rlang::try_fetch(...)
 11. |           | +-base::tryCatch(...)
 12. |           | | \-base (local) tryCatchList(expr, classes, parentenv, handlers)
 13. |           | |   \-base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
 14. |           | |     \-base (local) doTryCatch(return(expr), name, parentenv, handler)
 15. |           | \-base::withCallingHandlers(...)
 16. |           \-ggplot2 (local) f(l = layers[[i]], d = data[[i]])
 17. |             \-l$compute_aesthetics(d, plot)
 18. |               \-ggplot2 (local) compute_aesthetics(..., self = self)
 19. |                 \-ggplot2:::scales_add_defaults(...)
 20. |                   \-base::lapply(aesthetics[new_aesthetics], eval_tidy, data = data)
 21. |                     \-rlang (local) FUN(X[[i]], ...)
 22. \-base::.handleSimpleError(...)
 23.   \-rlang (local) h(simpleError(msg, call))
 24.     \-handlers[[1L]](cnd)
 25.       \-cli::cli_abort(...)
 26.         \-rlang::abort(...)</error>
    </testcase>
    <testcase time="0.138999999999896" classname="graph_snaps" name="plot_v1"/>
    <testcase time="0.0540000000000873" classname="graph_snaps" name="plot_v1"/>
    <testcase time="0.313999999999851" classname="graph_snaps" name="plot_v1">
      <skipped message="Reason: On CRAN ('test-graph-snaps.R:53:9')"/>
    </testcase>
    <testcase time="0.0760000000000218" classname="graph_snaps" name="plot_v2"/>
    <testcase time="0.0319999999999254" classname="graph_snaps" name="plot_v2"/>
    <testcase time="0.211000000000013" classname="graph_snaps" name="plot_v2">
      <skipped message="Reason: On CRAN ('test-graph-snaps.R:53:9')"/>
    </testcase>
    <testcase time="0.0690000000001874" classname="graph_snaps" name="plot_v3"/>
    <testcase time="0.0339999999998781" classname="graph_snaps" name="plot_v3"/>
    <testcase time="0.235000000000127" classname="graph_snaps" name="plot_v3">
      <skipped message="Reason: On CRAN ('test-graph-snaps.R:53:9')"/>
    </testcase>
    <testcase time="0.120999999999867" classname="graph_snaps" name="plot_v4">
      <error type="error" message="Error in `geom_point(data = . %&gt;% group_by(PARAMCD, ACTARM) %&gt;% mutate(outlier = ifelse(outliers(ratio),  ('test-graph-snaps.R:53:9')">Error in `geom_point(data = . %&gt;% group_by(PARAMCD, ACTARM) %&gt;% mutate(outlier = ifelse(outliers(ratio), 
    ratio, as.numeric(NA))), aes(x = PARAMCD, y = outlier), na.rm = T, 
    size = 2, position = position_dodge(1), show.legend = F)`: Problem while computing layer data.
i Error occurred in the 4th layer.
Caused by error in `mutate()`:
i In argument: `outlier = ifelse(outliers(ratio), ratio, as.numeric(NA))`.
i In group 1: `PARAMCD = AUCIFO`, `ACTARM = A: Drug X`.
Caused by error in `outliers()`:
! could not find function "outliers"</error>
    </testcase>
  </testsuite>
  <testsuite name="markdown-snaps" timestamp="2023-07-24T11:44:15Z" hostname="a61fa3a838a6" tests="16" skipped="16" failures="0" errors="0" time="6.402">
    <testcase time="1.19100000000003" classname="markdown_snaps" name="result_v1">
      <skipped message="Reason: On CRAN ('test-markdown-snaps.R:36:7')"/>
    </testcase>
    <testcase time="0.440000000000055" classname="markdown_snaps" name="result_v2">
      <skipped message="Reason: On CRAN ('test-markdown-snaps.R:36:7')"/>
    </testcase>
    <testcase time="0.648999999999887" classname="markdown_snaps" name="result_v3">
      <skipped message="Reason: On CRAN ('test-markdown-snaps.R:36:7')"/>
    </testcase>
    <testcase time="0.351000000000113" classname="markdown_snaps" name="result_v4">
      <skipped message="Reason: On CRAN ('test-markdown-snaps.R:36:7')"/>
    </testcase>
    <testcase time="0.344000000000051" classname="markdown_snaps" name="result_v6">
      <skipped message="Reason: On CRAN ('test-markdown-snaps.R:36:7')"/>
    </testcase>
    <testcase time="0.341999999999871" classname="markdown_snaps" name="result_v8">
      <skipped message="Reason: On CRAN ('test-markdown-snaps.R:36:7')"/>
    </testcase>
    <testcase time="0.335000000000036" classname="markdown_snaps" name="result_v9">
      <skipped message="Reason: On CRAN ('test-markdown-snaps.R:36:7')"/>
    </testcase>
    <testcase time="0.339999999999918" classname="markdown_snaps" name="result_v11">
      <skipped message="Reason: On CRAN ('test-markdown-snaps.R:36:7')"/>
    </testcase>
    <testcase time="1" classname="markdown_snaps" name="result_v1">
      <skipped message="Reason: On CRAN ('test-markdown-snaps.R:36:7')"/>
    </testcase>
    <testcase time="0.25" classname="markdown_snaps" name="result_v2">
      <skipped message="Reason: On CRAN ('test-markdown-snaps.R:36:7')"/>
    </testcase>
    <testcase time="0.117999999999938" classname="markdown_snaps" name="result_v3">
      <skipped message="Reason: On CRAN ('test-markdown-snaps.R:36:7')"/>
    </testcase>
    <testcase time="0.514999999999873" classname="markdown_snaps" name="result_v4">
      <skipped message="Reason: On CRAN ('test-markdown-snaps.R:36:7')"/>
    </testcase>
    <testcase time="0.134000000000015" classname="markdown_snaps" name="result_v5">
      <skipped message="Reason: On CRAN ('test-markdown-snaps.R:36:7')"/>
    </testcase>
    <testcase time="0.128000000000156" classname="markdown_snaps" name="result_v6">
      <skipped message="Reason: On CRAN ('test-markdown-snaps.R:36:7')"/>
    </testcase>
    <testcase time="0.134000000000015" classname="markdown_snaps" name="result_v7">
      <skipped message="Reason: On CRAN ('test-markdown-snaps.R:36:7')"/>
    </testcase>
    <testcase time="0.130999999999858" classname="markdown_snaps" name="result_v8">
      <skipped message="Reason: On CRAN ('test-markdown-snaps.R:36:7')"/>
    </testcase>
  </testsuite>
</testsuites>
